[package]
name = "lachs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
env_logger = "0.10.0"
log = "0.4.17"
phf = { version = "0.11.1", features = ["macros"] }
serial_int = "2.0.0"
thiserror = "1.0.38"
